.PHONY: clean All

All:
	@echo "----------Building project:[ Lab9 - Debug ]----------"
	@cd "Lab9" && "$(MAKE)" -f  "Lab9.mk"
clean:
	@echo "----------Cleaning project:[ Lab9 - Debug ]----------"
	@cd "Lab9" && "$(MAKE)" -f  "Lab9.mk" clean
