.PHONY: clean All

All:
	@echo "----------Building project:[ Lab6 - Debug ]----------"
	@cd "Lab6" && "$(MAKE)" -f  "Lab6.mk"
clean:
	@echo "----------Cleaning project:[ Lab6 - Debug ]----------"
	@cd "Lab6" && "$(MAKE)" -f  "Lab6.mk" clean
