.PHONY: clean All

All:
	@echo "----------Building project:[ Lab7 - Debug ]----------"
	@cd "Lab7" && "$(MAKE)" -f  "Lab7.mk"
clean:
	@echo "----------Cleaning project:[ Lab7 - Debug ]----------"
	@cd "Lab7" && "$(MAKE)" -f  "Lab7.mk" clean
